-- MySQL Script generated by MySQL Workbench
-- ter 08 set 2020 20:55:00 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`games` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  `data_lancamento` DATE NOT NULL,
  `is_jogo_do_ano` TINYINT(1) NOT NULL,
  `criacao` DATE NOT NULL,
  `modificacao` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plataformas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plataformas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `criacao` DATE NOT NULL,
  `modificacao` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`generos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `criacao` DATE NOT NULL,
  `modificacao` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`games_has_plataformas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`games_has_plataformas` (
  `games_id` INT NOT NULL,
  `plataformas_id` INT NOT NULL,
  PRIMARY KEY (`games_id`, `plataformas_id`),
  INDEX `fk_games_has_plataformas_plataformas1_idx` (`plataformas_id` ASC),
  INDEX `fk_games_has_plataformas_games_idx` (`games_id` ASC),
  CONSTRAINT `fk_games_has_plataformas_games`
    FOREIGN KEY (`games_id`)
    REFERENCES `mydb`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_has_plataformas_plataformas1`
    FOREIGN KEY (`plataformas_id`)
    REFERENCES `mydb`.`plataformas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`games_has_generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`games_has_generos` (
  `games_id` INT NOT NULL,
  `generos_id` INT NOT NULL,
  PRIMARY KEY (`games_id`, `generos_id`),
  INDEX `fk_games_has_generos_generos1_idx` (`generos_id` ASC),
  INDEX `fk_games_has_generos_games1_idx` (`games_id` ASC),
  CONSTRAINT `fk_games_has_generos_games1`
    FOREIGN KEY (`games_id`)
    REFERENCES `mydb`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_has_generos_generos1`
    FOREIGN KEY (`generos_id`)
    REFERENCES `mydb`.`generos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
